// <auto-generated />
using System;
using CardDemo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CardDemo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CardDemoDbContext))]
    [Migration("20260902162445_SharedLegacyData")]
    partial class SharedLegacyData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardDemo.Domain.Accounts.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("acct_id")
                        .UseCollation("C");

                    b.Property<string>("ActiveStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("acct_active_status");

                    b.Property<string>("AddressZip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("acct_addr_zip");

                    b.Property<decimal>("CashCreditLimit")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("acct_cash_credit_limit");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("acct_credit_limit");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("acct_curr_bal");

                    b.Property<decimal>("CurrentCycleCredit")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("acct_curr_cyc_credit");

                    b.Property<decimal>("CurrentCycleDebit")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("acct_curr_cyc_debit");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("acct_expiration_date");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("acct_group_id");

                    b.Property<DateOnly?>("OpenDate")
                        .HasColumnType("date")
                        .HasColumnName("acct_open_date");

                    b.Property<DateOnly?>("ReissueDate")
                        .HasColumnType("date")
                        .HasColumnName("acct_reissue_date");

                    b.HasKey("AccountId");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("CardDemo.Domain.Cards.Card", b =>
                {
                    b.Property<string>("CardNumber")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("card_num")
                        .UseCollation("C");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("card_acct_id")
                        .UseCollation("C");

                    b.Property<string>("ActiveStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("card_active_status");

                    b.Property<string>("CvvCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("card_cvv_cd");

                    b.Property<string>("EmbossedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("card_embossed_name");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("card_expiration_date");

                    b.HasKey("CardNumber");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_cards_card_acct_id");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("CardDemo.Domain.Cards.CardXref", b =>
                {
                    b.Property<string>("CardNumber")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("xref_card_num")
                        .UseCollation("C");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("xref_acct_id")
                        .UseCollation("C");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("xref_cust_id")
                        .UseCollation("C");

                    b.HasKey("CardNumber");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_card_xref_xref_acct_id");

                    b.ToTable("card_xref", (string)null);
                });

            modelBuilder.Entity("CardDemo.Domain.Customers.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cust_id")
                        .UseCollation("C");

                    b.Property<string>("AddressCountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("cust_addr_country_cd");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cust_addr_line_1");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cust_addr_line_2");

                    b.Property<string>("AddressLine3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cust_addr_line_3");

                    b.Property<string>("AddressStateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("cust_addr_state_cd");

                    b.Property<string>("AddressZip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cust_addr_zip");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("cust_dob");

                    b.Property<string>("EftAccountId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cust_eft_account_id");

                    b.Property<int>("FicoCreditScore")
                        .HasColumnType("integer")
                        .HasColumnName("cust_fico_credit_score");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("cust_first_name");

                    b.Property<string>("GovernmentIssuedId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cust_govt_issued_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("cust_last_name");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("cust_middle_name");

                    b.Property<string>("PhoneNumber1")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("cust_phone_num_1");

                    b.Property<string>("PhoneNumber2")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("cust_phone_num_2");

                    b.Property<string>("PrimaryCardHolderIndicator")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("cust_pri_card_holder_ind");

                    b.Property<string>("Ssn")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cust_ssn");

                    b.HasKey("CustomerId");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("CardDemo.Domain.Transactions.DisclosureGroup", b =>
                {
                    b.Property<string>("AccountGroupId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dis_acct_group_id")
                        .UseCollation("C");

                    b.Property<string>("TransactionTypeCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("dis_tran_type_cd")
                        .UseCollation("C");

                    b.Property<string>("TransactionCategoryCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("dis_tran_cat_cd")
                        .UseCollation("C");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("dis_int_rate");

                    b.HasKey("AccountGroupId", "TransactionTypeCode", "TransactionCategoryCode");

                    b.ToTable("disclosure_groups", (string)null);
                });

            modelBuilder.Entity("CardDemo.Domain.Transactions.Transaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tran_id")
                        .UseCollation("C");

                    b.Property<decimal>("Amount")
                        .HasPrecision(11, 2)
                        .HasColumnType("numeric(11,2)")
                        .HasColumnName("tran_amt");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tran_card_num")
                        .UseCollation("C");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("tran_cat_cd")
                        .UseCollation("C");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tran_desc");

                    b.Property<string>("MerchantCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tran_merchant_city");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("tran_merchant_id");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tran_merchant_name");

                    b.Property<string>("MerchantZip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tran_merchant_zip");

                    b.Property<DateTime?>("OriginalTimestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("tran_orig_ts");

                    b.Property<DateTime?>("ProcessedTimestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("tran_proc_ts");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tran_source");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("tran_type_cd")
                        .UseCollation("C");

                    b.HasKey("TransactionId");

                    b.HasIndex("ProcessedTimestamp")
                        .HasDatabaseName("ix_transactions_tran_proc_ts");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("CardDemo.Domain.Transactions.TransactionCategory", b =>
                {
                    b.Property<string>("TypeCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("tran_type_cd")
                        .UseCollation("C");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("tran_cat_cd")
                        .UseCollation("C");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tran_cat_type_desc");

                    b.HasKey("TypeCode", "CategoryCode");

                    b.ToTable("transaction_categories", (string)null);
                });

            modelBuilder.Entity("CardDemo.Domain.Transactions.TransactionCategoryBalance", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("trancat_acct_id")
                        .UseCollation("C");

                    b.Property<string>("TypeCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("trancat_type_cd")
                        .UseCollation("C");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("trancat_cd")
                        .UseCollation("C");

                    b.Property<decimal>("Balance")
                        .HasPrecision(11, 2)
                        .HasColumnType("numeric(11,2)")
                        .HasColumnName("tran_cat_bal");

                    b.HasKey("AccountId", "TypeCode", "CategoryCode");

                    b.ToTable("transaction_category_balances", (string)null);
                });

            modelBuilder.Entity("CardDemo.Domain.Transactions.TransactionType", b =>
                {
                    b.Property<string>("TypeCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("tran_type")
                        .UseCollation("C");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tran_type_desc");

                    b.HasKey("TypeCode");

                    b.ToTable("transaction_types", (string)null);
                });

            modelBuilder.Entity("CardDemo.Domain.Users.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("user_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("user_type");

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
