// Shared Prisma client for all batch jobs. Reuses the client generated by
// @carddemo/backend (modernized/backend/prisma/schema.prisma).
import { PrismaClient } from '@prisma/client';

export const prisma = new PrismaClient();
