package com.carddemo.cbtrn02c;
import com.carddemo.cbtrn02c.domain.*;import com.carddemo.cbtrn02c.repo.*;import com.carddemo.cbtrn02c.service.*;import java.math.*;import java.nio.file.*;import org.junit.jupiter.api.*;import static org.junit.jupiter.api.Assertions.*;
class BatchTests {
 static DalyTranRecord tran(String card,BigDecimal amt){DalyTranRecord d=new DalyTranRecord();d.id="T000000000000001";d.typeCd="PU";d.catCd="0001";d.source="TEST";d.desc="description";d.amt=amt;d.merchantId="123";d.merchantName="merchant";d.merchantCity="city";d.merchantZip="12345";d.cardNum=card;d.origTs="2024-01-02-00.00.00.000000";return d;}
 static AccountRecord acct(String id){AccountRecord a=new AccountRecord();a.acctId=id;a.activeStatus="A";a.creditLimit=new BigDecimal("1000");a.expirationDate="2025-12-31";return a;}
 static BatchFiles files(DalyTranRecord d,String card,String acct)throws Exception{Path p=Files.createTempDirectory("cb");BatchFiles f=new BatchFiles(p);f.daily.add(d);if(card!=null){CardXrefRecord x=new CardXrefRecord();x.cardNum=card;x.acctId=acct;f.xref.put(card,x);}if(acct!=null)f.accounts.put(acct,acct(acct));return f;}
 @Test void roundTripsLayouts(){DalyTranRecord d=tran("CARD",new BigDecimal("-12.34"));String s=d.format();assertEquals(350,s.length());assertEquals(d.amt,DalyTranRecord.parse(s).amt);CardXrefRecord x=new CardXrefRecord();x.cardNum="CARD";x.acctId="12";assertEquals(50,x.format().length());AccountRecord a=acct("12");assertEquals(300,a.format().length());TranCatBalRecord t=new TranCatBalRecord();t.acctId="12";t.typeCd="PU";t.catCd="0001";assertEquals(50,t.format().length());}
 @Test void validPostAndCreateBalance()throws Exception{BatchFiles f=files(tran("CARD",new BigDecimal("12.34")),"CARD","00000000001");var r=new TransactionPosterService().run(f);assertEquals(new TransactionPosterService.Result(1,0,0),r);assertEquals(new BigDecimal("12.34"),f.accounts.get("00000000001").currBal);assertEquals(1,f.transact.size());assertEquals(new BigDecimal("12.34"),f.tcatbal.values().iterator().next().tranCatBal);}
 @Test void reasonsAndOverwrite(){assertReason(100,null,null);assertReason(101,"CARD","00000000001");}
 void assertReason(int reason,String card,String aid){try{BatchFiles f=files(tran("CARD",BigDecimal.ONE),card,aid);var r=new TransactionPosterService().run(f);assertEquals(1,r.rejected());assertEquals(String.format("%04d",reason),f.rejects.get(0).substring(350,354));}catch(Exception e){throw new RuntimeException(e);}}
 @Test void overlimitAndExpirationFinal103()throws Exception{BatchFiles f=files(tran("CARD",new BigDecimal("1001")),"CARD","00000000001");f.accounts.get("00000000001").expirationDate="2020-01-01";var r=new TransactionPosterService().run(f);assertEquals(4,r.exitCode());assertEquals("0103",f.rejects.get(0).substring(350,354));}
 @Test void debitAccumulation()throws Exception{BatchFiles f=files(tran("CARD",new BigDecimal("-5.00")),"CARD","00000000001");var r=new TransactionPosterService().run(f);assertEquals(0,r.rejected());assertEquals(new BigDecimal("-5.00"),f.accounts.get("00000000001").currCycDebit);}
}
