// REQ-F-161, REQ-F-491 (InteractiveNavigationandMenuControl §17/§42):
// new transaction IDs are generated by incrementing the highest existing
// transaction ID by one, as a zero-padded 16-digit numeric string.

export function nextTransactionId(highestId: string | null): string {
  const current = highestId && /^\d+$/.test(highestId) ? BigInt(highestId) : 0n;
  return (current + 1n).toString().padStart(16, '0');
}
